# -*- coding: utf-8 -*-
{
    'name': 'Module Agen Andalan',
    'version': '1.0',
    'summary': 'Module Agen Andalan',
    'description': 'Module Agen Andalan',
    'category': 'Customs',
    'author': 'DPS',
    'website': '-',
    'license': 'AGPL-3',
    'depends': ['base','base_import','mail', 'account'],
    'data': [
            'security/security.xml',
            'views/dps_referenceAgen.xml',
            'views/dps_pricelist_views.xml',
            'views/dps_partner_views.xml',
            'views/dps_reference.xml',
            'views/dps_orders.xml',
            'views/dps_shipment.xml',
            'views/dps_container.xml',
            'views/dps_kemasan.xml',
            'views/inherit_invoicing.xml',
            'views/res_company_views.xml',
            'views/dps_nvocc.xml',
            'views/sequence.xml',
            'views/menu.xml',
            'reports/report_barcode.xml',
            'reports/report_barcode_template.xml',
            'security/ir.model.access.csv',
    ],
    'demo': [''],
    'installable': True,
    'auto_install': False,
    'models': ['models/res_company.py'],
}